# Generated by Django 5.1.6 on 2025-03-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('severity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='contact',
            new_name='phone',
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_analysis.disease')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='symptom_analysis.doctor'),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_analysis.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Precaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.CharField(max_length=200)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_analysis.disease')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_analysis.disease')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_analysis.patient')),
                ('symptoms', models.ManyToManyField(to='symptom_analysis.symptom')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(to='symptom_analysis.symptom'),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine', models.TextField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom_analysis.disease')),
            ],
        ),
    ]
