# Generated by Django 5.1.6 on 2025-03-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_analysis', '0002_disease_doctor_symptom_rename_contact_patient_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diets', to='symptom_analysis.disease'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disease',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(related_name='diseases', to='symptom_analysis.symptom'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='symptom_analysis.disease'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='symptom_analysis.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_histories', to='symptom_analysis.disease'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='symptom_analysis.patient'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='symptoms',
            field=models.ManyToManyField(related_name='patient_histories', to='symptom_analysis.symptom'),
        ),
        migrations.AlterField(
            model_name='precaution',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precautions', to='symptom_analysis.disease'),
        ),
        migrations.AlterField(
            model_name='precaution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='symptom_analysis.disease'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
