# Generated by Django 5.1.6 on 2025-03-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_analysis', '0003_alter_diet_disease_alter_diet_id_alter_disease_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='severity',
            field=models.IntegerField(default=1),
        ),
    ]
